// <auto-generated />
namespace MyEvernote.DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class EvernoteEntityChange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EvernoteEntityChange));
        
        string IMigrationMetadata.Id
        {
            get { return "201807141329078_EvernoteEntityChange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
